site_name: DeltaCore

repo_name: "2025.1-T01-FranquiAcademia"
repo_url: https://github.com/mdsreq-fga-unb/2024.2-T03-CafeDoSitio

nav:
  - Início: index.md
  - Introdução do Cliente: intro_client.md
  - Solução Proposta: solution.md
  - Estratégia de Produção:
      - Abordagem: approach.md
      - Ciclo de Vida: life_cicle.md
      - Processo: process.md

      


theme:
  name: material 
  language: pt-BR

  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.instant
    - navigation.top
    - navigation.tracking

  palette:
    - scheme: default
      primary: 'deep purple'
      accent: 'indigo'
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
        
    - scheme: slate
      primary: 'deep purple'
      accent: 'indigo'
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  
extra_css:
  - stylesheets/styles.css

markdown_extensions:
  - attr_list
