site_name: DeltaCore

repo_name: "2025.1-T01-FranquiAcademia"
repo_url: https://github.com/mdsreq-fga-unb/2025.1-T01-FranquiAcademia

nav:
  - Início: index.md
  - Visão do Produto e Projeto:
    - Cenário Atual do Cliente e Negócio: sections/intro_client.md
    - Solução Proposta: sections/solution.md
    - Estratégias de Engenharia de Software: sections/approach.md
    # - Lições Aprendidas: sections/documento-licoes.md


  #    - Introdução do Cliente: sections/intro_client.md
  #    - Solução Proposta: section/solution.md
  #    - Estratégia de Produção:
  #        - Abordagem: sections/approach.md
  #        - Ciclo de Vida: secions/life_cicle.md
  #        - Processo: sections/process.md
  #
      


theme:
  name: material 
  language: pt-BR

  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.instant
    - navigation.top
    - navigation.tracking

  palette:
    - scheme: default
      primary: 'deep purple'
      accent: 'indigo'
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
        
    - scheme: slate
      primary: 'deep purple'
      accent: 'indigo'
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  
extra_css:
  - stylesheets/styles.css

markdown_extensions:
  - attr_list
