site_name: DeltaCore

repo_name: "2025.1-T01-FranquiAcademia"
repo_url: https://github.com/mdsreq-fga-unb/2025.1-T01-FranquiAcademia

nav:
  - Início: index.md
  - Visão do Produto e Projeto:
    - Cenário Atual do Cliente e Negócio: sections/1-intro_client.md
    - Solução Proposta: sections/2-solution.md
    - Estratégias de Engenharia de Software: sections/3-approach.md
    - Cronograma e Entregas: sections/4-schedule.md
    - Interação entre Equipe e Cliente: sections/5-interection-po.md
    - Lições Aprendidas: sections/6-lessons-learned.md
    - Requisitos: sections/7-requirements.md
    - DoR & DoD: sections/8-DoR_DoD.md
    - Backlog: sections/9-BackLog.md
    - Engenharia de Requisitos: sections/10-engineering_requirements.md
  - PBB: sections/PBB/PBB.md
  - USM: sections/USM/USM.md
  - Casos de Uso: sections/UsesCases/Uses_cases.md
  - Reuniões:
    - 14/04: sections/reunioes/14-04.md
    - 28/04: sections/reunioes/28-04.md
    - 02/06: sections/reunioes/02-06.md
  - Entregas:
    - Entrega 1: entregas/1.md
    - Entrega 2: entregas/2.md
    - Entrega 3: entregas/3.md

theme:
  name: material 
  language: pt-BR

  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.instant
    - navigation.top
    - navigation.tracking

  palette:
    - scheme: default
      primary: 'deep purple'
      accent: 'indigo'
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
        
    - scheme: slate
      primary: 'deep purple'
      accent: 'indigo'
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  
extra_css:
  - stylesheets/styles.css

markdown_extensions:
  - attr_list
